name: 🐞 Bug Report
about: Use this template to report a bug
title: "[BUG] Brief summary"
labels: bug
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Provide a concise description of the issue.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug
      placeholder: |
        1. ...
        2. ...
        3. ...

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: Add screenshots or videos if applicable

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Select the OS where the issue occurs
      options:
        - Windows 10
        - Windows 11
        - macOS Monterey
        - macOS Ventura
        - Linux
        - Other

  - type: input
    id: browser-version
    attributes:
      label: Browser and Version
      description: e.g. Chrome 113, Firefox 100

  - type: input
    id: app-version
    attributes:
      label: Application Version
      description: e.g. 1.2.3

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any other relevant info or tips
