name: ✨ Feature Request
title: "[FEATURE] Brief summary"
labels: enhancement
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the feature request.
      placeholder: Describe the feature here
